### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by olegnoleg** [j-a-mercury/dragonsoul-gear#4]
What happened to the guild, man? I've created us a new "cool treats" guild for now, and we seem to have gotten a fair number of our members back so far, but we're all kind of at a loss as to what exactly happened. It doesn't seem likely you would simply kick us all or disband the guild without notice, so we're all kind of scratching our heads. Naz submitted a ticket to support & is awaiting an email back in reply, but we haven't seen you yet. And don't worry, I plan on promoting you back to leader once you've rejoined us in the new one, unless we can somehow get the original one restored. Thanks, buddy, hope to see you in there & hopefully clear some of this up shortly

**Comment by juviasuisei** [comment]
Thanks for the concern and sorry to cause confusion. I posted a message before I disbanded, but I'm guessing you weren't able to see it because the guild was closed. The group was getting increasingly less and less fun to manage and I was no longer having fun playing the game when I had to continually police and remove inactive/poorly performing members who were also getting increasingly vocal in their displeasure of how I was running my guild. I play to win and have fun, and it was feeling more and more like a job.

I considered passing ownership of the guild to you or Kellinator, as you and your other S5 guildies were by far the best part of our guild, but the name "cool treats" is significant to my wife and I and because you can't change the name of the guild after it has been created, I wasn't comfortable keeping the "cool treats" name out there since it would no longer be ours.

We've joined a new guild and are happy so far with their level of commitment, strategic play, friendliness, and overall activeness/attitude. I wish the game had private messaging, because I would have definitely have sent you and Kellinator a message first if possible. Clever of you to use Github; I was definitely considering using it this evening after work to reach out to you.

I understand that you might be too upset/frustrated with the outcome, but if you or Kellinator (or any of your other S5 guildies) want to come over to the new guild you're welcome. I'm not really interested in bringing any of the other members of the guild over. You and your S5ers were the best. Kellinator would like how talkative and friendly this new group is. They're called Dragon Born and they're all very high-level, dedicated, strategic players.

Again, apologies for the abruptness, if it was possible to rename a guild I would have kept it active and passed the torch instead.
